<?php

declare(strict_types=1);

/*
 * PrixAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PrixAPILib\Models;

use stdClass;

class RetrieveTransactionDetailsResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $reference;

    /**
     * @var string|null
     */
    private $prixAccount;

    /**
     * @var string|null
     */
    private $externalID;

    /**
     * @var float|null
     */
    private $amount;

    /**
     * Returns Reference.
     * The reference for the transaction
     */
    public function getReference(): ?string
    {
        return $this->reference;
    }

    /**
     * Sets Reference.
     * The reference for the transaction
     *
     * @maps reference
     */
    public function setReference(?string $reference): void
    {
        $this->reference = $reference;
    }

    /**
     * Returns Prix Account.
     * The Prix account associated with the transaction
     */
    public function getPrixAccount(): ?string
    {
        return $this->prixAccount;
    }

    /**
     * Sets Prix Account.
     * The Prix account associated with the transaction
     *
     * @maps prixAccount
     */
    public function setPrixAccount(?string $prixAccount): void
    {
        $this->prixAccount = $prixAccount;
    }

    /**
     * Returns External ID.
     * The external ID associated with the transaction
     */
    public function getExternalID(): ?string
    {
        return $this->externalID;
    }

    /**
     * Sets External ID.
     * The external ID associated with the transaction
     *
     * @maps externalID
     */
    public function setExternalID(?string $externalID): void
    {
        $this->externalID = $externalID;
    }

    /**
     * Returns Amount.
     * The amount of the transaction
     */
    public function getAmount(): ?float
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     * The amount of the transaction
     *
     * @maps amount
     */
    public function setAmount(?float $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->reference)) {
            $json['reference']   = $this->reference;
        }
        if (isset($this->prixAccount)) {
            $json['prixAccount'] = $this->prixAccount;
        }
        if (isset($this->externalID)) {
            $json['externalID']  = $this->externalID;
        }
        if (isset($this->amount)) {
            $json['amount']      = $this->amount;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
